[package]
name = "rust-vm"
version = "0.1.0"
authors = ["da.lum <david.lum91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
libc = "0.2.60"
termios = "0.3"
